authors:
  mheidari98:
    name: Mahdi Heidari
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/84391363
    url: https://github.com/mheidari98
  HIGHer:
    name: HIGHer
    description: Contributor
    avatar: https://avatars.githubusercontent.com/u/44268880
    url: https://github.com/HIGH0101

